Class BILL.EINV.DTO.JSA.InvoicemMedoutInfo Extends %RegisteredObject
{

Property category As %String(CAPTION = "就诊科室", XMLNAME = "category");

Property categorycode As %String(CAPTION = "就诊科室编码", XMLNAME = "category_code");

Property patientno As %String(CAPTION = "患者门诊号", XMLNAME = "patient_no");

Property caseno As %String(CAPTION = "病历号", XMLNAME = "case_no");

Property spdisname As %String(CAPTION = "特殊病种名称", XMLNAME = "sp_dis_name");

}
