Class web.DHCEntity.PCA.InvoicePrintData Extends (%RegisteredObject, %XML.Adaptor, DHCCPM.BLL.DHCXMLReader)
{

Parameter XMLIGNORENULL = 1;

Parameter XMLNAME = "Invoice";

Property Index As %String(TRUNCATE = 1);

Property PrtDate As %String(TRUNCATE = 1);

Property PrtTime As %String(TRUNCATE = 1);

Property FairType As %String(TRUNCATE = 1);

Property FairTypeFlag As %String(TRUNCATE = 1);

Property AdmReason As %String(TRUNCATE = 1);

Property PatientID As %String(TRUNCATE = 1);

Property PatName As %String(TRUNCATE = 1);

Property AdmLocDesc As %String(TRUNCATE = 1);

Property Amt As %String(TRUNCATE = 1);

Property AmtDX As %String(TRUNCATE = 1);

Property UserName As %String(TRUNCATE = 1);

Property UserCode As %String(TRUNCATE = 1);

Property InvNO As %String(TRUNCATE = 1);

Property CateDetail As %String(TRUNCATE = 1);

Property ItemDetail As %String(TRUNCATE = 1);

Property DepDesc As %String(TRUNCATE = 1);

Property DocDesc As %String(TRUNCATE = 1);

Property SessionType As %String(TRUNCATE = 1);

Property TimeRange As %String(TRUNCATE = 1);

Property SeqNo As %String(TRUNCATE = 1);

Property RoomNo As %String(TRUNCATE = 1);

Property RoomFloor As %String(TRUNCATE = 1);

Property RegFee As %String(TRUNCATE = 1);

Property AppFee As %String(TRUNCATE = 1);

Property OtherFee As %String(TRUNCATE = 1);

Property ClinicGroupCode As %String(TRUNCATE = 1);

Property BoroughDesc As %String(TRUNCATE = 1);

Property PrnRegFee As %String(TRUNCATE = 1);

Property PrnCheckFee As %String(TRUNCATE = 1);

Property PrnReCheckFee As %String(TRUNCATE = 1);

Property PrnMRFee As %String(TRUNCATE = 1);

Property PrnCardFee As %String(TRUNCATE = 1);

Property AdmDate As %String(TRUNCATE = 1);

Property RegDate As %String(TRUNCATE = 1);

}
