$(document).ready(function(){
    var dataBox=$("#dataBox"),
        dataDialog=$("#dataDialog")
        dataForm=$("#dataForm");

    dataBox.datagrid({
        idField:"RowId",
        treeField:"Code",
        title:"手术模块",
        url:dhcclinic.QueryService,
        columns:[[
            {field:"Code",title:"代码",width:180},
            {field:"Description",title:"描述",width:120},
            {field:"DataModuleDesc",title:"数据模块",width:120},
            {field:"ElementID",title:"关联元素",width:120},
            {field:"Icon",title:"图标",width:120},
            {field:"ExecFunc",title:"执行函数",width:120},
            {field:"LinkModuleDesc",title:"链接模块",width:120},
            {field:"LinkModuleURL",title:"链接url",width:210},
        ]],
        queryParams:{
            ClassName:dhcclinic.QueryServiceClass,
            QueryName:"FindOperActions",
            Arg1:$("#filterDataModule").combobox("getValue"),
            ArgCnt:1
        },
        fit:true,
        singleSelect:true,
        rownumbers:true,
        pagination:true,
        toolbar:"#dataTools",
        pageSize:50,
        pageList:[50,100,200]
    });

    $("#filterDataModule,#DataModule,#LinkModule").combobox({
        valueField:"RowId",
        textField:"Description",
        url:dhcclinic.QueryService,
        queryParams:{
            ClassName:dhcclinic.QueryServiceClass,
            QueryName:"FindDataModule",
            Arg1:"QueryFilter",
            Arg2:"",
            Arg3:"",
            ArgCnt:3
        }

    });
    $("#btnQuery").linkbutton({
        onClick:function(){
            dataBox.datagrid("reload",{
                ClassName:dhcclinic.QueryServiceClass,
                QueryName:"FindOperActions",
                Arg1:$("#filterDataModule").combobox("getValue"),
                ArgCnt:1
            })
        }
    });
    dataForm.form({
        url:dhcclinic.DataService,
        onSubmit:function(){
            var isValid=$(this).form("validate");
            if(!isValid){
                dataDialog.dialog("close");
            }
            return isValid;
        },
        queryParams:{
            ClassName:"DHCAN.OperAction"
        },
        success:function(data){
            showOperMessage(data,"保存",function(){
                dataForm.form("clear");
                dataBox.datagrid("reload");
                if(dataDialog)
                {
                    dataDialog.dialog("close");
                }
            })
        }
    })
    if(dataDialog){
        dataDialog.dialog({
            buttons:[
                {
                    text:"保存",
                    iconCls:"icon-save",
                    handler:function(){
                        dataForm.submit();
                    }
                },{
                    text:"取消",
                    iconCls:"icon-cancel",
                    handler:function(){
                       dataDialog.dialog("close");
                    }
                }
            ],
        })
    }
    $("#btnAdd").linkbutton({
        onClick:function(){
            $("#RowId").val("");
            if(dataDialog){
                dataDialog.dialog({
                    title:"新增",
                    iconCls:"icon-add"
                })
                dataDialog.dialog("open");
            }else{
                dataForm.submit();
            }
        }
    });
    $("#btnEdit").linkbutton({
        onClick:function(){
            if(hasRowSelected(dataBox,true)){
                if(dataDialog){
                    dataDialog.dialog({
                        title:"编辑",
                        iconCls:"icon-edit"
                    })
                    var selectedRow=dataBox.datagrid("getSelected");
                    dataForm.form("load",selectedRow);
                    dataDialog.dialog("open");
                }else{
                    dataForm.submit();
                }
            }
        }
    });

    $("#btnDel").linkbutton({
        onClick:function(){
            if(hasRowSelected(dataBox,true)){
                $.messager.comfirm("确认","是否删除该数据记录？",function(result){
                    if(result){
                        var msg=removeData("DHCAN.OperAction",$("#RowId").val())
                        showOperMessage(msg,"删除",function(){
                            dataForm.form("clear");
                            dataBox.datagrid("reload");     
                        });
                    }
                });
            }
        }
    });


});