Class CHSS.PersonDiagnose Extends %Persistent [ ClassType = persistent, Owner = {_SYSTEM}, ProcedureBlock, SqlRowIdName = DiagnoseRowId, SqlTableName = PersonDiagnose ]
{

Storage Default
{
<Data name="PersonDiagnoseDefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
</Data>
<DataLocation>^CHSS.PersonDiagnoseD</DataLocation>
<DefaultData>PersonDiagnoseDefaultData</DefaultData>
<ExtentSize>100000</ExtentSize>
<IdLocation>^CHSS.PersonDiagnoseD</IdLocation>
<IndexLocation>^CHSS.PersonDiagnoseI</IndexLocation>
<StreamLocation>^CHSS.PersonDiagnoseS</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
