Class CT.WS.entity.EStdDictionary Extends (%RegisteredObject, %XML.Adaptor) [ ClassType = "", Inheritance = right, ProcedureBlock ]
{

Property Code As %String(TRUNCATE = 1);

Property Description As %String(TRUNCATE = 1);

Property DicAliasCol As %String(TRUNCATE = 1);

Property DicCodeCol As %String(TRUNCATE = 1);

Property DicDescCol As %String(TRUNCATE = 1);

Property ID As %String(TRUNCATE = 1);

Property Name As %String(TRUNCATE = 1);

Property TableName As %String(TRUNCATE = 1);

Property Condition As %String(TRUNCATE = 1);

Property ConditionCode As %String(TRUNCATE = 1);

Property Sequence As %Integer;

Property SystemCode As %String(TRUNCATE = 1);

//add by Candyxu20120607 为排序

}
