/// Function: 分配资源到科室 实体类
/// Creator:  sunfengchao
/// CreateDate:2016-2-29
Class web.Entity.CT.RBResourceForEQ Extends (%RegisteredObject, web.DHCEntity.ELAbstract) [ ProcedureBlock ]
{

Parameter PersistentClassName = "web.Entity.CT.RBResourceForEQ";

Property RESRowId1 As %String;

Property RESCTLOCDR As %String;

Property RESEQDR As %String;

Property RESDateActiveFrom As %String;

Property RESDateActiveTo As %String;

}
