Class web.Entity.CT.SSUserOtherLogonLoc Extends (%RegisteredObject, web.DHCEntity.ELAbstract) [ ProcedureBlock ]
{

Parameter PersistentClassName = "web.Entity.CT.SSUserOtherLogonLoc";

Property OTHLLRowId As %String;

// 用户

Property OTHLLParRef As %String;

// 科室

Property OTHLLCTLOCDR As %String;

// 安全组

Property OTHLLUserGroupDR As %String;

// 医院

Property OTHLLHospitalDR As %String;

// 开始日期

Property OTHLLStartDate As %String;

// 截止日期

Property OTHLLEndDate As %String;

}
