Class web.PACLiquorColour Extends (%Library.RegisteredObject, websys.Abstract) [ ClassType = "", Inheritance = right, Not ProcedureBlock ]
{

Parameter BUILD = 28;

Property dummy As %Library.String(TRUNCATE = 1);

Parameter SQLCODE = "LIQCOLOR_Code";

Parameter SQLDATEFROM = "LIQCOLOR_DateFrom";

Parameter SQLDATETO = "LIQCOLOR_DateTo";

Parameter SQLDESCRIPTION = "LIQCOLOR_Desc";

Parameter SQLROWID = "LIQCOLOR_RowId";

}
